<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="62207" started-at="2018-09-28T10:17:36Z" finished-at="2018-09-28T10:18:38Z">
    <groups>
    </groups>
    <test name="登录失败测试：数据驱动" duration-ms="62207" started-at="2018-09-28T10:17:36Z" finished-at="2018-09-28T10:18:38Z">
      <class name="org.webdriver.mindaiappui.cases.LoginTest">
        <test-method status="PASS" signature="setup(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:org.webdriver.mindaiappui.cases.LoginTest@4d826d77]" name="setup" is-config="true" duration-ms="30149" started-at="2018-09-28T18:17:36Z" finished-at="2018-09-28T18:18:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[AndroidDriver]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[127.0.0.1:4723]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[mdcn_420.apk]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Android Emulator]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[4.4.2]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.mdcn.mdonline]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[.activity.WelcomeActivity]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[Android]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="beforeclass()[pri:0, instance:org.webdriver.mindaiappui.cases.LoginTest@4d826d77]" name="beforeclass" is-config="true" duration-ms="0" started-at="2018-09-28T18:18:06Z" finished-at="2018-09-28T18:18:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeclass -->
        <test-method status="FAIL" signature="loginFail(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:org.webdriver.mindaiappui.cases.LoginTest@4d826d77]" name="loginFail" duration-ms="26065" started-at="2018-09-28T18:18:06Z" description="登录失败用例" data-provider="longinData" finished-at="2018-09-28T18:18:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[13620025002]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[登录成功]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[设置手势密码成功]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at org.webdriver.mindaiappui.utils.ElementAction.click(ElementAction.java:257)
	at org.webdriver.mindaiappui.cases.LoginTest.loginFail(LoginTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginFail -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:org.webdriver.mindaiappui.cases.LoginTest@4d826d77]" name="tearDown" is-config="true" duration-ms="4591" started-at="2018-09-28T18:18:34Z" finished-at="2018-09-28T18:18:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- org.webdriver.mindaiappui.cases.LoginTest -->
    </test> <!-- 登录失败测试：数据驱动 -->
  </suite> <!-- Suite -->
</testng-results>
